version: '3.8'

services:
  dune-gpt:
    build: .
    container_name: dune-gpt
    ports:
      - "8000:8000"
    environment:
      # Required environment variables - set these in your .env file
      - ARGO_API_USERNAME=${ARGO_API_USERNAME}
      - ARGO_API_KEY=${ARGO_API_KEY}
      - DUNE_DOCDB_USERNAME=${DUNE_DOCDB_USERNAME}
      - DUNE_DOCDB_PASSWORD=${DUNE_DOCDB_PASSWORD}
      
      # Optional environment variables
      - DUNE_INDICO_ACCESS_KEY=${DUNE_INDICO_ACCESS_KEY:-}
      - DOC_LIMIT_DOCDB=${DOC_LIMIT_DOCDB:-50}
      - DOC_LIMIT_INDICO=${DOC_LIMIT_INDICO:-50}
      - HOST=${HOST:-0.0.0.0}
      - PORT=${PORT:-8000}
      - DEBUG=${DEBUG:-false}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - DEFAULT_TOP_K=${DEFAULT_TOP_K:-3}
      - LLM_TEMPERATURE=${LLM_TEMPERATURE:-0.1}
      - LLM_TOP_P=${LLM_TOP_P:-0.9}
      - LLM_MODEL=${LLM_MODEL:-gpt4o}
      - EMBEDDING_MODEL=${EMBEDDING_MODEL:-multi-qa-mpnet-base-dot-v1}
    volumes:
      # Persist FAISS index data
      - faiss_data:/app/data/faiss
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  faiss_data:
    driver: local 