"""AskDUNE Slack application.

Handles incoming direct messages, retrieves context from a vector database,
and generates RAG-based responses using the configured LLM provider.
"""

import os
import re
import json
from typing import Any, Callable, Dict, Iterable, Tuple

from slack_bolt import App
from slack_bolt.adapter.socket_mode import SocketModeHandler
from slack_sdk.web import WebClient
from markdown_to_mrkdwn import SlackMarkdownConverter

from config import (
    STORE,
    CHROMA_PATH,
    LLM_PROVIDER,
    ARGO_API_USERNAME,
    ARGO_API_KEY,
    K_DOCS,
    DEFAULT_TOP_K,
    validate_config,
)
from src.utils.logger import get_logger

logger = get_logger(__name__)
converter = SlackMarkdownConverter()
app = App(token=os.environ.get("SLACK_BOT_TOKEN"))


def _initialize_db_manager(store: str, path: str) -> Any:
    """Initializes the vector database manager based on configuration.

    Args:
        store: The database provider type ("faiss" or "chroma").
        path: Filepath to the database directory.

    Returns:
        An instance of the selected database manager.

    Raises:
        ValueError: If the store configuration is unsupported.
    """
    if store == "faiss":
        from src.indexing.faiss_manager_langchain import FAISSManager
        return FAISSManager(path)

    if store == "chroma":
        from src.indexing.chroma_manager import ChromaManager
        return ChromaManager(path)

    raise ValueError(f"Unsupported STORE configuration: {store}")


def _initialize_llm_client(
    provider: str, username: str | None = None, api_key: str | None = None
) -> Any:
    """Initializes the LLM API client based on configuration.

    Args:
        provider: The LLM provider name ("argo" or "fermilab").
        username: Optional API username for authentication.
        api_key: Optional API key for authentication.

    Returns:
        An instance of the selected LLM client.

    Raises:
        ValueError: If the provider configuration is unsupported.
    """
    if provider == "argo":
        from src.api.argo_client import ArgoAPIClient
        return ArgoAPIClient(username, api_key)

    if provider == "fermilab":
        from src.api.fermilab_client import FermilabAPIClient
        return FermilabAPIClient()

    raise ValueError(f"Unsupported LLM_Provider configuration: {provider}")


db_manager = _initialize_db_manager(STORE, CHROMA_PATH)
llm_client = _initialize_llm_client(LLM_PROVIDER, ARGO_API_USERNAME, ARGO_API_KEY)


def _update_status(client: WebClient, channel: str, ts: str, status: str = "") -> None:
    """Updates the Slack assistant thread status indicator."""
    try:
        client.assistant_threads_setStatus(
            channel_id=channel, thread_ts=ts, status=status
        )
    except Exception as e:
        logger.warning(f"Failed to update status to '{status}': {e}")


def _parse_llm_stream(chunks: Iterable[str]) -> Tuple[str, list]:
    """Extracts text segments and source metadata from an LLM stream response.

    Args:
        chunks: Stream of text fragments and metadata tags (e.g., "SOURCES:").

    Returns:
        A tuple containing the full consolidated response text and a list of sources.
    """
    text_segments = []
    sources = []

    for chunk in chunks:
        if chunk.startswith("STATUS:"):
            continue

        if chunk.startswith("SOURCES:"):
            try:
                json_str = chunk.removeprefix("SOURCES:").strip()
                sources = json.loads(json_str)
            except json.JSONDecodeError as e:
                logger.warning(f"Failed to parse response sources JSON: {e}")
            continue

        text_segments.append(chunk)

    return "".join(text_segments), sources


def _format_reply(raw_text: str, sources: list) -> str:
    """Converts raw markdown text and appends formatted reference links for Slack.

    Args:
        raw_text: Raw markdown text generated by the LLM.
        sources: List of metadata dictionaries containing source URLs.

    Returns:
        Slack-compatible mrkdwn formatted string.
    """
    formatted_text = converter.convert(raw_text)

    links = [
        f"{idx}. <{source['url']}>"
        for idx, source in enumerate(sources, 1)
        if source.get("url")
    ]

    if links:
        formatted_text += "\n\n*Sources:*\n" + "\n".join(links)

    return formatted_text


@app.message(re.compile(".*"))
def message_dms(
    message: Dict[str, Any], say: Callable[..., Any], client: WebClient
) -> None:
    """Listens for and processes incoming Slack direct messages.

    Queries the vector database for relevant context, sends it to the LLM client,
    and replies to the user with a formatted response.

    Args:
        message: Slack message event payload.
        say: Function to send a message back to the thread channel.
        client: Slack WebClient instance for API communication.
    """
    if (
        message.get("channel_type") != "im"
        and message.get("subtype") is not None
        and "bot_id" in message
    ):
        return

    query = message.get("text")
    channel = message.get("channel")
    ts = message.get("ts")

    if not (query and channel and ts):
        return

    logger.info(f"DM from {message.get('user')}: {query}")
    _update_status(client, channel, ts, "is thinking...")

    try:
        context_snippets, references = db_manager.search(
            query, k_docs=K_DOCS, top_k=DEFAULT_TOP_K
        )

        chunks = llm_client.chat_completion(
            query, context="\n\n".join(context_snippets), links=references
        )
        raw_text, sources = _parse_llm_stream(chunks)

        if raw_text:
            say(text=_format_reply(raw_text, sources))

    except Exception as e:
        logger.exception(f"Error processing DM: {e}")
        say(f"Sorry, I encountered an error processing your message.")

    finally:
        _update_status(client, channel, ts)


def main() -> None:
    """Validates configuration parameters and initializes the Slack Socket Mode handler."""
    validate_config()
    logger.info("Starting AskDUNE Slack application")
    SocketModeHandler(app, os.environ["SLACK_APP_TOKEN"]).start()


if __name__ == "__main__":
    main()
